# THIS IS A VERBOSE EXAMPLE OF A GROUP INVENTORY FILE FOR COMMON E-SERIES STORAGE SYSTEM CONFIGURATIONS.

# Storage System Credentials for Interacting with Web Services Proxy
# ------------------------------------------------------------------
#eseries_ssid: 1                                          # Storage array identifier.
#eseries_api_url: https://192.168.10.100/devmgr/v2        # Url for the SANtricity Web Service Proxy. Example: https://192.168.10.100/devmgr/v2
#eseries_api_username: admin                              # Username for the web services proxy.
#eseries_api_password: password                           # Password for the web services proxy.
#eseries_validate_certs: False                            # Whether the SSL certificates should be verified. (boolean)


# Storage Pool Default Policy Specifications
# ------------------------------------------
#eseries_storage_pool_state: present                      # Default storage pool state. Choices: present, absent
#eseries_storage_pool_raid_level: raidDiskPool            # Default volume group raid level. Choices: raid0, raid1, raid5, raid6, raidDiskPool
#eseries_storage_pool_secure_pool: no                     # Default for storage pool drive security. This flag will enable the security at rest feature. Type: boolean
#eseries_storage_pool_criteria_drive_count:               # Default storage pool drive count.
#eseries_storage_pool_reserve_drive_count:                # Default reserve drive count for drive reconstruction for storage pools using dynamic disk pool (raid level must be raidDiskPool)
#eseries_storage_pool_criteria_min_usable_capacity:       # Default minimum required capacity for storage pools.
#eseries_storage_pool_criteria_drive_type:                # Default drive type for storage pools. Choices: hdd, ssd
#eseries_storage_pool_criteria_size_unit: gb              # Default unit size for all storage pool related sizing. Choices: bytes, b, kb, mb, gb, tb, pb, eb, zb, yb
#eseries_storage_pool_criteria_drive_min_size:            # Default minimum drive size for storage pools.
#eseries_storage_pool_criteria_drive_require_da:          # Default for whether storage pools are required to have data assurance (DA) compatible drives. Type: boolean
#eseries_storage_pool_criteria_drive_require_fde:         # Default for whether storage pools are required to have drive security compatible drives. Type: boolean
#eseries_storage_pool_remove_volumes:                     # Default policy for deleting volumes prior to removing storage pools.
#eseries_storage_pool_erase_secured_drives:               # Default policy for erasing the content drives during create and delete storage pool operations. Type: boolean


# Volume Default Policy Specifications
# ------------------------------------
#eseries_volume_state: present                            # Default volume state. Choices: present, absent
#eseries_volume_size_unit: gb                             # Default unit size for all volume sizing options.
#eseries_volume_size:                                     # Default volume size or the presented size for thinly provisioned volumes.
#eseries_volume_data_assurance_enabled:                   # Default for whether data assurance(DA) is required to be enabled.
#eseries_volume_segment_size_kb:                          # Default segment size measured in kib.
#eseries_volume_read_cache_enable:                        # Default for read caching which will cache all read requests.
#eseries_volume_read_ahead_enable:                        # Default for read ahead caching; this is good for sequential workloads to cache subsequent blocks.
#eseries_volume_write_cache_enable:                       # Default for write caching which will cache all writes.
#eseries_volume_thin_provision:                           # Default for whether volumes should be thinly provisioned.
#eseries_volume_thin_volume_repo_size:                    # Default for actually allocated space for thinly provisioned volumes.
#eseries_volume_thin_volume_max_repo_size:                # Default for the maximum allocated space allowed for thinkly provisioned volumes.
#eseries_volume_thin_volume_expansion_policy:             # Default thin volume expansion policy. Choices: automatic, manual
#eseries_volume_thin_volume_growth_alert_threshold:       # Default thin volume growth alert threshold. (10-99)
#eseries_volume_ssd_cache_enabled:                        # Default for ssd cache which will enable the volume to use an existing SSD cache on the storage array.
#eseries_volume_host:                                     # Default host for all volumes
#eseries_volume_workload_name:                            # Default workload tag name
#eseries_volume_metadata:                                 # Default metadata


# Storage Pool-Volume Default Specifications
# ------------------------------------------
#eseries_lun_mapping_host:                                # Default host for all volumes not specifically give a host either in common_volume_configuration or in eseries_storage_pool_configuration.


# Controller Interface Port Default Policy Specifications
# -------------------------------------------------------
#eseries_controller_port_state: enabled                   # Generally specifies whether a controller port definition should be applied Choices: enabled, disabled
#eseries_controller_port_config_method: dhcp              # General port configuration method definition for both controllers. Choices: static, dhcp
#eseries_controller_port_gateway:                         # General port IPv4 gateway for both controllers.
#eseries_controller_port_subnet_mask:                     # General port IPv4 subnet mask for both controllers.
#eseries_controller_port_mtu: 9000                        # General port maximum transfer units (MTU) for both controllers. Any value greater than 1500 (bytes).


# Target Discovery Default Policy Specifications
# ----------------------------------------------
#eseries_target_name:                                      # iSCSI target name
#eseries_target_ping: True                                 # Enables ICMP ping response from the configured iSCSI ports (boolean)
#eseries_target_unnamed_discovery: True                    # Whether the iSCSI target iqn should be returned when an initiator performs a discovery session.
#eseries_target_chap_secret:                               # iSCSI chap secret.
                                                           #  * NOTE add the argument --extra-vars "eseries_target_chap_secret_update=True" to ansible-playbook execution command to update

# Host Default Policy Specifications
# ----------------------------------
#eseries_host_force_port: True                             # Default for whether ports are to be allowed to be re-assigned (boolean)
#eseries_host_remove_unused_hostgroup: True                # Forces any unused groups to be removed


# Initiator-Target Protocol Variable Defaults
# -------------------------------------------
#eseries_initiator_protocol: iscsi     # This variable defines which protocol the storage array will use. Choices: iscsi, fc, sas
#eseries_initiator_configuration:      # Note that the following commands produce a unique list of IQNs or WWNs of the interfaces used, line separated.
#  fc:
#    eseries_initiator_command:
#      linux: "systool -c fc_host -v | grep port_name | cut -d '\"' -f 2 | cut -d 'x' -f 2 | sort | uniq"
#      windows: "(Get-InitiatorPort | Where-Object -P ConnectionType -EQ 'Fibre Channel' | Select-Object -Property PortAddress | Format-Table -AutoSize -HideTableHeaders | Out-String).trim()"
#  iscsi:
#    eseries_initiator_command:
#      linux: "cat /etc/iscsi/initiatorname.iscsi | grep iqn. | cut -d'=' -f 2 && iscsiadm -m iface | grep iqn. | cut -d',' -f 5 | sort | uniq"
#      windows: "(get-initiatorPort | select-object -property nodeaddress | sort-object | get-unique | ft -autoSize | out-string -stream | select-string iqn | out-string).trim()"
#  sas:
#    eseries_initiator_command:
#      linux: "systool -c scsi_host -v | grep host_sas_address | cut -d '\"' -f 2 | cut -d 'x' -f 2"
#      windows: "(Get-InitiatorPort | Where-Object -P ConnectionType -EQ 'SAS' | Select-Object -Property PortAddress | Format-Table -AutoSize -HideTableHeaders | Out-String).trim()"
