---
- name: Make sure we defined the NetApp eSDS RPM location
  when: >
    solidfire_element_rpm is not undefined and
    na_sf_filename is not undefined and
    solidfire_element_rpm is match('http|ftp')
  block:
    # else we'll clear the old file and download to localhost
    - name: Make sure we have no old copies of the NetApp eSDS RPM on the host
      delegate_to: localhost
      file:
        path: "/tmp/{{ na_sf_filename }}"
        state: absent
      when: >
        na_sf_filename is not undefined and
        solidfire_element_rpm is not match('http|ftp')

    - name: Make sure the NetApp eSDS RPM is available
      delegate_to: localhost
      get_url:
        url: "{{ solidfire_element_rpm }}"
        dest: "/tmp/{{ na_sf_filename }}"
        validate_certs: "{{ na_sf_validate_certs | bool }}"
        use_proxy: "{{ na_sf_use_proxy | bool }}"
      when: >
        solidfire_element_rpm is not undefined and
        na_sf_filename is not undefined and
        solidfire_element_rpm is match('http|ftp')

    - set_fact:
      solidfire_element_rpm_path: >-
        "{% if soldidfire_element_rpm is not undefined
            and solidfire_element_rpm is match('http|ftp') %}/tmp/{{ na_sf_filename }}
        {% else %}{{ solidfire_element_rpm }}{% endif %}"
