# -----------------------------------
# Check for existing credential match
# -----------------------------------

- name: .....check credential {{ item.host_login }} - {{ item.host_name }}

  uri:
    url: "{{ deploy_api_url }}/security/credentials?hostname={{ item.host_name }}"
    method: GET
    headers:
      Content-Type: "application/json"
    body_format: json
    user: "{{ deploy_login }}"
    password: "{{ deploy_pwd }}"
    status_code: 200
    validate_certs: False

  register: get_credential_response

# --------------------------------
# Add Credenntial if doesn't exist
# --------------------------------

- name: .....add credential {{ item.host_login }} - {{ item.host_name }}

  uri:
    url: "{{ deploy_api_url }}/security/credentials"
    method: POST
    headers:
      Content-Type: "application/json"
    body:
      hostname: "{{ item.host_name }}"
      password: "{{ lookup('template', 'host2pwd.j2') | trim }}"
      type: "host"
      username: "{{ item.host_login }}"
    body_format: json
    user: "{{ deploy_login }}"
    password: "{{ deploy_pwd }}"
    status_code: 202
    validate_certs: False
  when:
    - get_credential_response.json.num_records == 0

  register: add_credential_response
