# ----------------------------------
# Register Host
# - ESXi host NOT managed by vCenter
# - KVM host
# ----------------------------------

# ------------------------------------------------------
# Check the host_id_list for existing registered hosts
# If the specified host is not in the list than register
# - host_id_list is created by get_host_ids task
# ------------------------------------------------------

- name: Register Host - {{ item.host_name }}

  uri:
    url: "{{ deploy_api_url }}/hosts"
    method: POST
    headers:
      Content-Type: "application/json"
    body: '{"hosts": [{"hypervisor_type": "{{ hypervisor }}","name": "{{ item.host_name }}"}]}'
    body_format: json
    user: "{{ deploy_login }}"
    password: "{{ deploy_pwd }}"
    status_code: 202
    validate_certs: False
  register: host_register_response
  when: item.host_name not in ( host_id_list | map(attribute='host_name') )

# ----------------------------
# Monitor the registration job
# ----------------------------

- name: .....monitor host registration job

  include_tasks: monitor_job.yml
  vars:
    job_id: "{{ host_register_response.json.job.id }}"
    job_retries: "{{ monitor_host_retries }}"
    job_delay: "{{ monitor_host_delay }}"
  when:
    - item.host_name not in ( host_id_list | map(attribute='host_name') )
