---
- name: Ensure teamdctl cores are ignored in ABRT
  include_tasks: ignore-teamdctl-cores-in-abrt.yml
  when: sf_ignore_teamdctl_abrt_cores

- name: Ensure we loaded facts for nodes
  setup:
  when: (ansible_facts is undefined or
    (ansible_facts is defined and not ansible_facts)) or
    (sf_node_facts is undefined or
    (sf_node_facts is defined and not sf_node_facts))

- name: Make sure all required variables are defined
  include_tasks: verify-variables.yml

- name: Ensure we loaded the Minimum Specification Checks
  include_tasks: ./min-specification/min-specification-checks.yml
  when: >
    na_sf_deactivate_checks is undefined or
    (na_sf_deactivate_checks is defined and not na_sf_deactivate_checks)

- name: Make sure the NetApp eSDS RPM is installed
  include_tasks: install-rpm.yml

- name: Ensure the NetApp eSDS environment is configured
  include_tasks: update-config.yml

- name: "Ensure the NetApp eSDS service management is loaded"
  include_tasks: start-solidfire.yml
