# THIS EXAMPLE IS A CONCISE EXAMPLE OF HOST INVENTORY FILE WITH DESCRIPTIONS AND IS INTENDED FOR USERS THAT NEED ONLY COMMON CONFIGURATION. SEE THE
#     eseries_storage_full_example.yml FILE FOR MORE OPTIONS.

# Default Storage System Credentials for Interacting with Web Services REST API
# -----------------------------------------------------------------------------
#eseries_ssid: 1                                    # Storage array identifier.
#eseries_api_url: https://192.168.10.100/devmgr/v2  # Url for the web services api. Example: https://192.168.10.100/devmgr/v2
#eseries_api_username: admin                        # Username for the web services api.
#eseries_api_password: password                     # Password for the web services api.
#eseries_validate_certs: False                      # Whether the SSL certificates should be verified. (boolean)


# Controller Interface Port Policy Specifications
# -----------------------------------------------
#eseries_controller_port_config_method: dhcp        # General port configuration method definition for both controllers. Choices: static, dhcp
#eseries_controller_port_gateway:                   # General port IPv4 gateway for both controllers.
#eseries_controller_port_subnet_mask:               # General port IPv4 subnet mask for both controllers.
#eseries_controller_port_mtu: 9000                  # General port maximum transfer units (MTU) for both controllers. Any value greater than 1500 (bytes).
#eseries_controller_port:
#  controller_a:                                    # Controller A port definition.
#    ports:                                         # List containing ports definitions
#      - channel:                                   # Channel of the port to modify. This will be a numerical value that represents the port; typically read left to right on the HIC.
#        state:                                     # Whether the port should be enabled.
#        config_method:                             # Port configuration method Choices: static, dhcp
#        address:                                   # Port IPv4 address
#        gateway:                                   # Port IPv4 gateway
#        subnet_mask:                               # Port IPv4 subnet_mask
#  controller_b:                                    # Controller B port definition.
#    ports:                                         # List containing ports definitions
#      - channel:                                   # Channel of the port to modify. This will be a numerical value that represents the port; typically read left to right on the HIC.
#        state:                                     # Whether the port should be enabled.
#        config_method:                             # Port configuration method Choices: static, dhcp
#        address:                                   # Port IPv4 address
#        gateway:                                   # Port IPv4 gateway
#        subnet_mask:                               # Port IPv4 subnet_mask


# Storage Pool-Volume Policy Specifications
# -----------------------------------------
#   Name schemes: Storage pool and volume names can be used to specify a naming scheme to produce a list of storage pools and volumes. The schemes are defined by
#                 brackets which can be used to specify a range of lowercase letters, uppercase letters, single digit numbers, any top-level inventory
#                 variables, and the current defined storage pool (volume only). Add [pool] to any volume name and it will be replaced with the group name.

#eseries_storage_pool_configuration:
#  - name:                         # Name or name scheme (see above) for the storage pool.
#    state:                        # Specifies whether the storage pool should exist (present, absent).
#    raid_level                    # Volume group raid level. Choices: raid0, raid1, raid5, raid6, raidDiskPool (Default: raidDiskPool)
#    criteria_drive_count:         # Default storage pool drive count.
#    criteria_drive_type:          # Default drive type for storage pools. Choices: hdd, ssd
#    common_volume_configuration:  # Any option that can be specified at the volume level can be generalized here at the storage pool level.
#    volumes:                      # List of volumes associated the storage pool.
#      - state:                    # Specifies whether the volume should exist (present, absent)
#        name:                     # (required) Name or name scheme (see above) for the volume(s) to be created in the storage pool(s)
#        host:                     # host or host group for the volume should be mapped to.
#        size:                     # Size of the volume or presented size of the thinly provisioned volume.
#        size_unit:                # Unit size for the size, thin_volume_repo_size, and thin_volume_max_repo_size. Choices: bytes, b, kb, mb, gb, tb, pb, eb, zb, yb
#        workload_name:            # Name of the volume's workload.
#        metadata:                 # Dictionary containing arbitrary entries normally used for defining the volume(s) workload.
