---
- name: Create Vserver
  na_ontap_svm:
    state: present
    name: "{{ item.name }}"
    root_volume: "{{ item.name }}_root"
    root_volume_aggregate: "{{ item.aggr }}"
    root_volume_security_style: "{{ 'ntfs' if item.protocol.lower() is search('cifs') else 'unix' }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ vservers }}"
  when: vservers != None
- name: Setup FCP
  na_ontap_fcp:
    state: present
    service_state: started
    vserver: "{{ item.name }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ vservers }}"
  when: item.protocol.lower() is search("fcp")
- name: Setup iSCSI
  na_ontap_iscsi:
    state: present
    service_state: started
    vserver: "{{ item.name }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ vservers }}"
  when: item.protocol.lower() is search("iscsi")
- name: Modify adapter
  na_ontap_ucadapter:
    state: present
    adapter_name: "{{ item.adapter_name }}"
    node_name: "{{ item.node_name }}"
    mode: fc
    type: target
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  with_items:
    "{{ fcp }}"
  when: fcp != None
- name: Create Interface
  na_ontap_interface:
    state: present
    interface_name: "{{ item.name }}"
    home_port: "{{ item.port }}"
    home_node: "{{ item.node }}"
    role: data
    protocols: "{{ item.protocol }}"
    admin_status: up
    failover_policy: local-only
    firewall_policy: mgmt
    is_auto_revert: true
    address: "{{ item.address }}"
    netmask: "{{ item.netmask }}"
    vserver: "{{ item.vserver }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ lifs }}"
  when: lifs != None
- name: Add default route
  na_ontap_net_routes:
    state: present
    vserver: "{{ item.vserver }}"
    username: "{{ username }}"
    password: "{{ password }}"
    hostname: "{{ hostname }}"
    destination: "{{ item.destination }}"
    gateway: "{{ item.gateway }}"
    metric: 30
    https: true
    validate_certs: false
  with_items:
    "{{ gateway }}"
  when: gateway != None
- name: Create DNS
  na_ontap_dns:
    state: present
    vserver: "{{ item.vserver }}"
    domains: "{{ item.dns_domains }}"
    nameservers: "{{ item.dns_nameservers }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ vserver_dns }}"
  when: vserver_dns !=None
- name: Create CIFS Server
  na_ontap_cifs_server:
    state: present
    vserver: "{{ item.vserver }}"
    domain: "{{ item.domain }}"
    cifs_server_name: "{{ item.cifs_server_name }}"
    force: "{{ 'false' if item.force is not defined else item.force }}"
    admin_password: "{{ admin_password }}"
    admin_user_name: "{{ admin_user_name }}"
    ou: "{{ item.ou | default(omit) }}"
    service_state: started
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ cifs }}"
  when: cifs != None
- name: Create NFS Server
  na_ontap_nfs:
    state: present
    service_state: started
    vserver: "{{ item.name }}"
    nfsv3: enabled
    nfsv4: disabled
    nfsv41: disabled
    tcp: enabled
    udp: enabled
    vstorage_state: disabled
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ vservers }}"
  when: 
    - item.protocol.lower() is search("nfs")
    - ontap_facts.ontap_version > "120"
- name: Create NFS Server
  na_ontap_nfs:
    state: present
    service_state: started
    vserver: "{{ item.name }}"
    nfsv3: enabled
    nfsv4: disabled
    nfsv41: disabled
    vstorage_state: disabled
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ vservers }}"
  when: 
    - item.protocol.lower() is search("nfs")
    - ontap_facts.ontap_version < "130"
- name: Setup default NFS rule
  na_ontap_export_policy_rule:
    state: present
    policy_name: default
    vserver: "{{ item.name }}"
    client_match: 0.0.0.0/0
    ro_rule: any
    rw_rule: none
    protocol: any
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    ontapi: "{{ ontap_facts.ontap_version }}"
    https: true
    validate_certs: false
  with_items:
    "{{ vservers }}"
  when:
    item.protocol.lower() is search("nfs")
