---
# netapp_eseries_iscsi/tasks/main.yml
- name: Ensure modules and plugins are properly located
  import_tasks: setup.yml
  tags:
    - ansible_setup

- name: Configure NetApp E-Series storage system disk pool configuration
  import_tasks: storage_pool_present.yml
  tags:
    - storage_pools

- name: Configure NetApp E-Series storage system volume configuration
  import_tasks: volume.yml
  tags:
    - volumes

- name: Configure NetApp E-Series storage system disk pool configuration
  import_tasks: storage_pool_absent.yml
  tags:
    - storage_pools

- name: Configure storage system's hosts/hostgroups initiators
  import_tasks: initiator.yml
  tags:
    - initiators

- name: Map storage system's volumes to host objects
  import_tasks: lun_mapping.yml
  tags:
    - lun_mappings

- name: Configure controllers iSCSI interface ports
  import_tasks: port.yml
  tags:
    - ports
  when: not eseries_initiator_configuration[eseries_initiator_protocol]["eseries_skip_port_task"]