---
# netapp_eseries_iscsi/tasks/storage_pool_absent.yml
- name: Configure NetApp E-Series storage system disk pool configuration
  netapp_e_storagepool:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    raid_level: "{{ item.raid_level }}"
    secure_pool: "{{ item.secure_pool }}"
    criteria_drive_count:  "{{ item.criteria_drive_count }}"
    reserve_drive_count:  "{{ item.reserve_drive_count }}"
    criteria_min_usable_capacity:  "{{ item.criteria_min_usable_capacity }}"
    criteria_drive_type:  "{{ item.criteria_drive_type }}"
    criteria_size_unit:  "{{ item.criteria_size_unit }}"
    criteria_drive_min_size:  "{{ item.criteria_drive_min_size }}"
    criteria_drive_require_da:  "{{ item.criteria_drive_require_da }}"
    criteria_drive_require_fde:  "{{ item.criteria_drive_require_fde }}"
    remove_volumes:  "{{ item.remove_volumes }}"
    erase_secured_drives:  "{{ item.erase_secured_drives }}"
  when: item.state == 'absent'
  loop: "{{ storage_pool_configuration }}"
  vars:
    storage_pool_configuration: "{%include ([netapp_eseries_relative_template_path, 'generate_storage_pool_configuration_list.j2']|join('')) %}"
