---
# netapp_eseries_iscsi/tasks/storage_pool_present.yml
- name: Configure NetApp E-Series storage system disk pool configuration
  netapp_e_storagepool:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    raid_level: "{{ item.raid_level | default(omit) }}"
    secure_pool: "{{ item.secure_pool | default(omit) }}"
    criteria_drive_count:  "{{ item.criteria_drive_count | default(omit) }}"
    reserve_drive_count:  "{{ item.reserve_drive_count | default(omit) }}"
    criteria_min_usable_capacity:  "{{ item.criteria_min_usable_capacity | default(omit) }}"
    criteria_drive_type:  "{{ item.criteria_drive_type | default(omit) }}"
    criteria_size_unit:  "{{ item.criteria_size_unit | default(omit) }}"
    criteria_drive_min_size:  "{{ item.criteria_drive_min_size | default(omit) }}"
    criteria_drive_require_da:  "{{ item.criteria_drive_require_da | default(omit) }}"
    criteria_drive_require_fde:  "{{ item.criteria_drive_require_fde | default(omit) }}"
    remove_volumes:  "{{ item.remove_volumes | default(omit) }}"
    erase_secured_drives:  "{{ item.erase_secured_drives | default(omit) }}"
  when: item.state == 'present'
  loop: "{{ storage_pool_configuration }}"
  vars:
    storage_pool_configuration: "{%include ([netapp_eseries_relative_template_path, 'generate_storage_pool_configuration_list.j2']|join('')) %}"
