---
# netapp_eseries_iscsi/tasks/volume.yml
- name: Configure Netapp E-Series storage system disk pool volume configuration
  netapp_e_volume:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    storage_pool_name: "{{ item.storage_pool_name | default(omit) }}"
    size: "{{ item.size | default(omit) }}"
    size_unit: "{{ item.size_unit | default(omit) }}"
    workload_name: "{{ item.workload_name | default(omit) }}"
    metadata: "{{ item.metadata | default(omit) }}"
  loop: "{{ storage_pool_configuration | default(omit) }}"
  vars:
    storage_pool_configuration: "{%include ([netapp_eseries_relative_template_path, 'generate_volume_configuration_list.j2']|join('')) %}"
